### PR TITLE
Create GitHub workflow for building and pushing the operator image

### LINKED ISSUE #1: Move the Operator container image to `redhat-sap-cop` Org in Quay
Move the operator container image `quay.io/redhat-sap/hybris-operator:0.1` and any other custom container image specifically related to this operator under `redhat-sap-cop` Org

### PR DESCRIPTION
**Pull request by xieshenzh**
Create GitHub workflow for building and pushing the operator image to quay.io .

In order for the workflow to work:

1. Create a Quay [robot account](https://docs.quay.io/glossary/robot-accounts.html).
2. [Create GitHub secret](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-a-repository) `QUAY_USERNAME` and `QUAY_TOKEN` with the Quay robot account username and token for the GitHub Action to push the image.

### CODE REVIEW

**Review by makentenza — APPROVED** [review]
LGTM

**Review by tejones — APPROVED** [review]
LGTM2

**Comment by makentenza** [comment]
@xieshenzh I think this good enough for now. Going forward could we modify the workflow so the image tag is created out from the branch/tag information, using `latest` for master and branch/tag ID for the rest? Just thinking about how we make changes in the future without "breaking" the operator.

**Comment by xieshenzh** [comment]
> @xieshenzh I think this good enough for now. Going forward could we modify the workflow so the image tag is created out from the branch/tag information, using `latest` for master and branch/tag ID for the rest? Just thinking about how we make changes in the future without "breaking" the operator.

Sure. We can also manage the version in the source code, because the workflow yaml file is also part of the source code.

**Pull request merged**
